applicatie/gelre_airport/Models/Passagier.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gelre_airport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passagier
    {
        public Passagier()
        {
            this.PassagierVoorVlucht = new HashSet<PassagierVoorVlucht>();
        }
    
        public int passagiernummer { get; set; }
        public string naam { get; set; }
        public string geslacht { get; set; }
        public System.DateTime geboortedatum { get; set; }
    
        public virtual ICollection<PassagierVoorVlucht> PassagierVoorVlucht { get; set; }
    }
}

applicatie/gelre_airport/Controllers/ObjectsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using gelre_airport.Models;
using System.Data.Entity.Infrastructure;

namespace gelre_airport.Controllers
{
    public class ObjectsController : Controller
    {
        private GelreAirportEntities db = new GelreAirportEntities();

        // GET: Objects
        public ActionResult Index()
        {
            return View(db.Object.ToList());
        }

        // GET: Objects/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            gelre_airport.Models.Object @object = db.Object.Find(id);
            if (@object == null)
            {
                return HttpNotFound();
            }
            return View(@object);
        }

        // GET: Objects/Create
        public ActionResult Create()
        {
            ViewBag.passagiernummer = new SelectList(db.PassagierVoorVlucht, "passagiernummer", "stoel");
            return View();
        }

        // POST: Objects/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "volgnummer,passagiernummer,vluchtnummer,gewicht")] gelre_airport.Models.Object @object)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Object.Add(@object);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                ViewBag.passagiernummer = new SelectList(db.PassagierVoorVlucht, "passagiernummer", "stoel", @object.passagiernummer);
                ViewBag.vluchtnummer = new SelectList(db.PassagierVoorVlucht, "vluchtnummer", "stoel", @object.vluchtnummer);
            }
            catch (DbUpdateException e)
            {
                ViewBag.error = e.GetBaseException().Message;
            }
            return View(@object);
        }

        // GET: Objects/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            gelre_airport.Models.Object @object = db.Object.Find(id);
            if (@object == null)
            {
                return HttpNotFound();
            }
            ViewBag.passagiernummer = new SelectList(db.PassagierVoorVlucht, "passagiernummer", "stoel", @object.passagiernummer);
            return View(@object);
        }

        // POST: Objects/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "volgnummer,passagiernummer,vluchtnummer,gewicht")] gelre_airport.Models.Object @object)
        {
            if (ModelState.IsValid)
            {
                db.Entry(@object).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.passagiernummer = new SelectList(db.PassagierVoorVlucht, "passagiernummer", "stoel", @object.passagiernummer);
            return View(@object);
        }

        // GET: Objects/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            gelre_airport.Models.Object @object = db.Object.Find(id);
            if (@object == null)
            {
                return HttpNotFound();
            }
            return View(@object);
        }

        // POST: Objects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            gelre_airport.Models.Object @object = db.Object.Find(id);
            db.Object.Remove(@object);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

applicatie/gelre_airport/Controllers/PassagiersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using gelre_airport.Models;
using System.Data.Entity.Infrastructure;
using System.Data.SqlClient;

namespace gelre_airport.Controllers
{
    public class PassagiersController : Controller
    {
        private GelreAirportEntities db = new GelreAirportEntities();

        // GET: Passagiers
        public ActionResult Index()
        {
            return View(db.Passagier.ToList());
        }

        // GET: Passagiers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Passagier passagier = db.Passagier.Find(id);
            if (passagier == null)
            {
                return HttpNotFound();
            }
            return View(passagier);
        }

        public ActionResult AllDetails(int id, string vluchtnummer)
        {
            try
            {
                Passagier passagier = db.Passagier.Find(id);
                if (passagier == null)
                {
                    return HttpNotFound();
                }
                int vluchtnr = int.Parse(vluchtnummer);
                Vlucht vlucht = db.Vlucht.Find(vluchtnr);
                ViewBag.vlucht = vlucht;
                List<gelre_airport.Models.Object> baggage = new List<gelre_airport.Models.Object>();
                baggage = db.Object.Where(q => q.passagiernummer == id && q.vluchtnummer == vluchtnr).ToList();
                ViewBag.baggage = baggage;
                PassagierVoorVlucht pvv = db.PassagierVoorVlucht.Find(passagier.passagiernummer, vluchtnr);
                ViewBag.pvv = pvv;
                return View(passagier);
            } catch (InvalidOperationException e) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
        }

        // GET: Passagiers/Create
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Search([Bind(Include = "passagiernaam,vluchtnummer,luchthaven,maatschappij,vertrekdatum")] SearchModel searchCriteria)
        {
            if (searchCriteria.passagiernaam == null)
            {
                searchCriteria.passagiernaam = "";
            }
            if (searchCriteria.vluchtnummer == null)
            {
                searchCriteria.vluchtnummer = "";
            }
            if (searchCriteria.luchthaven == null)
            {
                searchCriteria.luchthaven = "";
            }
            if (searchCriteria.maatschappij == null)
            {
                searchCriteria.maatschappij = "";
            }
            string query = @"select p.passagiernummer as passagiernummer, p.naam as passagiernaam, CAST(pvv.vluchtnummer AS VARCHAR) as vluchtnummer, l.naam as luchthaven, m.naam as maatschappij, CAST(v.vertrektijdstip as Date) as vertrekdatum
                    FROM Passagier p
	                    INNER JOIN PassagierVoorVlucht pvv ON pvv.passagiernummer = p.passagiernummer
	                    INNER JOIN Vlucht v ON v.vluchtnummer = pvv.vluchtnummer
	                    INNER JOIN Luchthaven l ON l.luchthavencode = v.luchthavencode
	                    INNER JOIN Maatschappij m ON m.maatschappijcode = v.maatschappijcode
                    WHERE p.naam LIKE '%' + @p0 + '%'
                    AND CONVERT(VARCHAR, pvv.vluchtnummer) LIKE '%' + @p1 + '%'
                    AND l.naam LIKE '%' + @p2 + '%'
                    AND m.naam LIKE '%' + @p3 + '%' ";
            DbRawSqlQuery<SearchModel> data = null;
            if (!searchCriteria.vertrekdatum.ToString().Equals("1-1-0001 00:00:00"))
            {
                query += "AND CAST(v.vertrektijdstip AS DATE) = @p4 ORDER BY p.passagiernummer";
                data = db.Database.SqlQuery<SearchModel>(query, searchCriteria.passagiernaam, searchCriteria.vluchtnummer, 
                    searchCriteria.luchthaven, searchCriteria.maatschappij, searchCriteria.vertrekdatum.Date);
            }
            else
            {
                query += "ORDER BY p.passagiernummer";
                data = db.Database.SqlQuery<SearchModel>(query, searchCriteria.passagiernaam, 
                    searchCriteria.vluchtnummer, searchCriteria.luchthaven, searchCriteria.maatschappij);
            }
            return View(data.ToList());
        }

        // POST: Passagiers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "passagiernummer,naam,geslacht,geboortedatum")] Passagier passagier)
        {
            if (ModelState.IsValid)
            {
                db.Passagier.Add(passagier);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(passagier);
        }

        // GET: Passagiers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Passagier passagier = db.Passagier.Find(id);
            if (passagier == null)
            {
                return HttpNotFound();
            }
            return View(passagier);
        }

        // POST: Passagiers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "passagiernummer,naam,geslacht,geboortedatum")] Passagier passagier)
        {
            if (ModelState.IsValid)
            {
                db.Entry(passagier).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(passagier);
        }

        // GET: Passagiers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Passagier passagier = db.Passagier.Find(id);
            if (passagier == null)
            {
                return HttpNotFound();
            }
            return View(passagier);
        }

        // POST: Passagiers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Passagier passagier = db.Passagier.Find(id);
            db.Passagier.Remove(passagier);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

applicatie/gelre_airport/Views/Passagiers/AllDetails.cshtml
@model gelre_airport.Models.Passagier

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Passagier</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.naam)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.naam)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.geslacht)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.geslacht)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.geboortedatum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.geboortedatum)
        </dd>

    </dl>
</div>
<div>
    <h4>Passagier voor vlucht:</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>Balienummer</dt>
        <dd>@ViewBag.pvv.balienummer</dd>
        <dt>Inchecktijdstip</dt>
        <dd>@ViewBag.pvv.inchecktijdstip</dd>
        <dt>Stoel</dt>
        <dd>@ViewBag.pvv.stoel</dd>
    </dl>
    @using (Html.BeginForm("Edit", "PassagierVoorVluchts", FormMethod.Post))
    {
        <input type="submit" value="Bewerken" class="btn-default" />
        @Html.TextBox("passagiernummer", ViewBag.pvv.passagiernummer as string)
        @Html.TextBox("vluchtnummer", @ViewBag.pvv.vluchtnummer as string)
        @Html.TextBox("inchecktijdstip", (@ViewBag.pvv.inchecktijdstip).ToString() as string)
        @Html.TextBox("stoel", @ViewBag.pvv.stoel as string)
    }
</div>
<div>
    <h4>Vlucht</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>Vluchtnummer</dt>
        <dd>@ViewBag.vlucht.vluchtnummer</dd>   
        <dt>Gatecode</dt>
        <dd>@ViewBag.vlucht.gatecode</dd>
        <dt>Maatschappijcode</dt>
        <dd>@ViewBag.vlucht.maatschappijcode</dd>
        <dt>Luchthavencode</dt>
        <dd>@ViewBag.vlucht.luchthavencode</dd>
        <dt>Vliegtuigtype</dt>
        <dd>@ViewBag.vlucht.vliegtuigtype</dd>
        <dt>Maximaal aantal passagiers:</dt>
        <dd>@ViewBag.vlucht.max_aantal_psgrs</dd>
        <dt>Maximaal totaal gewicht</dt>
        <dd>@ViewBag.vlucht.max_ppgewicht</dd>
        <dt>Vertrektijdstip</dt>
        <dd>@ViewBag.vlucht.vertrektijdstip</dd>
        <dt>Aankomsttijdstip</dt>
        <dd>@ViewBag.vlucht.aankomsttijdstip</dd>
    </dl>
</div>
<div>
    <h4>Baggage</h4>
    <p>@Html.ActionLink("Create", "Create", "Objects", null, null)</p>
    <hr />
    @foreach (var item in ViewBag.baggage)
    {
        <dl class="dl-horizontal">
            <dt>Volgnummer</dt>
            <dd>@item.volgnummer</dd>
            <dt>Gewicht</dt>
            <dd>@item.gewicht</dd>
            <dt>Vluchtnummer</dt>
            <dd>@item.vluchtnummer</dd>
            <dt>Passagiernummer</dt>
            <dd>@item.passagiernummer</dd>
        </dl>
        <div>
            @Html.ActionLink("Edit", "Edit", "Objects", new { id = item.volgnummer }, null) |
            @Html.ActionLink("Delete", "Delete", "Objects", new { id = item.volgnummer }, null) |
        </div>
    }            
</div>

applicatie/gelre_airport/Views/Passagiers/Create.cshtml
@model gelre_airport.Models.Passagier

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Passagier</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.passagiernummer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.passagiernummer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.passagiernummer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.naam, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.naam, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.naam, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.geslacht, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.geslacht, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.geslacht, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.geboortedatum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.geboortedatum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.geboortedatum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

applicatie/gelre_airport/Views/Passagiers/Delete.cshtml
@model gelre_airport.Models.Passagier

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Passagier</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.naam)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.naam)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.geslacht)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.geslacht)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.geboortedatum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.geboortedatum)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

applicatie/gelre_airport/Views/Passagiers/Details.cshtml
@model gelre_airport.Models.Passagier

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Passagier</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.naam)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.naam)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.geslacht)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.geslacht)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.geboortedatum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.geboortedatum)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.passagiernummer }) |
    @Html.ActionLink("Back to List", "Index")
</p>

applicatie/gelre_airport/Views/Passagiers/Edit.cshtml
@model gelre_airport.Models.Passagier

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Passagier</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.passagiernummer)

        <div class="form-group">
            @Html.LabelFor(model => model.naam, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.naam, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.naam, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.geslacht, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.geslacht, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.geslacht, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.geboortedatum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.geboortedatum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.geboortedatum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

applicatie/gelre_airport/Views/Passagiers/Index.cshtml
@model IEnumerable<gelre_airport.Models.Passagier>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.passagiernummer)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.naam)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.geslacht)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.geboortedatum)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.passagiernummer)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.naam)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.geslacht)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.geboortedatum)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.passagiernummer }) |
            @Html.ActionLink("Details", "Details", new { id=item.passagiernummer }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.passagiernummer })
        </td>
    </tr>
}

</table>

applicatie/gelre_airport/Views/Passagiers/Search.cshtml
@model IEnumerable<gelre_airport.Models.SearchModel>
@{
    ViewBag.Title = "Search";
}
<h2>Search</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.passagiernummer)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.passagiernaam)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.vluchtnummer)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.luchthaven)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.maatschappij)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.vertrekdatum)
        </th>
        <th>
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.passagiernummer)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.passagiernaam)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.vluchtnummer)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.luchthaven)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.maatschappij)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.vertrekdatum.Date)
            </td>
            <td>
                @Html.ActionLink("Details", "AllDetails", new { id = item.passagiernummer, vluchtnummer = item.vluchtnummer })
            </td>
        </tr>
    }
    <p>
        @Html.ActionLink("Back to List", "Index")
    </p>
</table>